apiVersion: v1
kind: Secret
metadata:
  name: workspace-secret
type: Opaque
stringData:
  DEV_PASSWORD: "{{ .Values.auth.devPassword }}"
  GIT_USER_NAME: "{{ .Values.auth.gitUserName }}"
  GIT_USER_EMAIL: "{{ .Values.auth.gitUserEmail }}"
