apiVersion: v1
kind: Service
metadata:
  name: workspace
spec:
  type: {{ .Values.service.type }}
  selector:
    app: workspace
  ports:
    - name: rdp
      port: {{ .Values.service.ports.rdp.port }}
      targetPort: 3389
      nodePort: {{ .Values.service.ports.rdp.nodePort }}
    - name: ssh
      port: {{ .Values.service.ports.ssh.port }}
      targetPort: 22
      nodePort: {{ .Values.service.ports.ssh.nodePort }}
